# Quartzine — Configuration
# ------------------------------

# Comportement au branchement USB
# Valeurs : vm | normal | ask
mode = "ask"

# Délai avant action automatique (en secondes, 0 = pas de délai)
timeout = 30

# Dossier de sortie des rapports (s'il y en a)
report_dir = "/var/log/quartzine/reports"


# path of the virtual disk
path_to_virtual_disk = "/home/mathieu/projects/Quartzine/vm/disk/vm.qcow2"

# path of the iso
path_to_iso = "/home/mathieu/Bureau/alpine.iso"


# root of project
project_root = "/home/mathieu/projects/Quartzine"
